/* SEARCH - CREATOR */
export const SET_FILTER_SEARCH_CARS = 'SET_FILTER_SEARCH_CARS';
export const SET_FILTER_CATEGORIES_SEARCH_CAR = 'SET_FILTER_CATEGORIES_SEARCH_CAR';
export const SET_AVAILABILITY_SUCCESS = 'SET_CARS_BY_FILTER_SUCCESS';
export const SET_PLACES_SUCCESS = 'SET_PLACES_SUCCESS';
export const SET_CATEGORY_SELECTED = 'SET_CATEGORY_SELECTED';
export const SET_CATEGORIE_SUCCESS = 'SET_CATEGORIE_SUCCESS';
export const UPDATE_CATEGORY_DEFAULT = 'UPDATE_CATEGORY_DEFAULT';
export const CLEAN_LIST_CARS = 'CLEAN_LIST_CARS';

/* SEARCH - SAGA */
export const GET_AVAILABILITY_REQUEST = 'GET_AVAILABILITY_REQUEST';
export const GET_PLACES_REQUEST = 'GET_PLACES_REQUEST';
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const SET_FORMAT_FILTER_AVAILABILITY = 'SET_FORMAT_FILTER_AVAILABILITY';

/* NAVIGATION - CREATOR */
export const SET_PAGE_ACTIVE = 'SET_PAGE_ACTIVE';

/* ACTION BUTTON SEARCH AVAILABILITY */
export const ACTION_BUTTON_FIND_CAR = 'ACTION_BUTTON_FIND_CAR';
export const ACTION_REDIRECT = 'ACTION_REDIRECT';
export const ACTION_SEARCH_AVAILABILITY = 'ACTION_SEARCH_AVAILABILITY';

/* SPINNER */
export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';

/* CONFIGURATIONS - SAGA */
export const GET_CONFIGURATIONS_REQUEST = 'GET_CONFIGURATIONS_REQUEST';
export const SET_CONFIGURATIONS_SUCCESS = 'SET_CONFIGURATIONS_SUCCESS';
